List formatting
resolvetosavelives/healthicons pull request #14
Opened 2021-05-29 22:46 UTC by dburka

Lots of formatting:

- Fixed several broken icons
- Formatted the icons lists in the grid
- Made the link color purple
- Added an About page
- Added a Footer to the homepage

2021-05-29 23:02 UTC, nburka requested changes

2021-05-29 23:02 UTC, nburka commented on src/pages/about.tsx
> +            <h2 id="license">License</h2>
i think this should use `name`

2021-05-29 23:02 UTC, nburka commented on src/pages/about.tsx
> +            <h2 id="license">License</h2>
also, if we add an anchor here, we could add it for the other H2's on this page

2021-05-29 23:09 UTC, dburka commented on src/components/TopBar.module.scss
> +  text-decoration: none !important;
No, but I can't figure it out :/

2021-05-29 23:09 UTC, dburka commented on src/components/TopBar.module.scss
> +  color: #fff !important;
No, but I can't figure it out :/

2021-05-30 00:47 UTC, merged

2021-05-30 01:16 UTC, nburka commented on src/components/TopBar.module.scss
> +  color: #fff !important;
I made an Issue to fix this later

2021-05-30 01:16 UTC, nburka commented on src/components/TopBar.module.scss
> +  text-decoration: none !important;
I made an Issue to fix this later