New icons (updated the OG images, tags)
resolvetosavelives/healthicons pull request #141
Opened 2021-09-07 09:47 UTC by dburka

Added Covid icons, a bunch of Body icons, and a few Symbols as well.

2021-09-07 12:47 UTC, nburka requested changes

2021-09-07 12:47 UTC, nburka commented on public/icons/meta-data.json
> +   "calendar",
lower case tags should be title case

2021-09-07 12:47 UTC, nburka commented on public/icons/meta-data.json
> +   "ache",
more lower case tags

2021-09-07 12:47 UTC, nburka commented on public/icons/meta-data.json
> +   "covid",
lower case

2021-09-07 12:47 UTC, nburka commented on public/icons/meta-data.json
> +   "covid",
lower case

2021-09-08 10:24 UTC, dburka commented
Fixed the lowercase tags. Will merge. Thanks @nburka

2021-09-08 10:24 UTC, merged